chore: unify prettier to 3.4.2
redhat-developer/rhdh-plugins pull request #212
Opened 2024-12-19 12:51 UTC by mareklibra

Unifies prettier to a single 3.4.2 version through-out the whole repo.

The first commit is result of a manual change, the later one is the result of calling the prettier from the root-level and then from every workspace.

2024-12-19 12:55 UTC, batzionb approved these changes

2024-12-19 12:59 UTC, christoph-jerolimov commented on .prettierignore
> +**/generated/**
isn't this the same as `generated` ?
```suggestion
generated
```

2024-12-19 13:04 UTC, christoph-jerolimov commented on workspaces/orchestrator/plugins/orchestrator-backend/static/generated/envelope/combined.bundle.js
You want that this files are part of the repo? It looks like it's formatted also if you have added the generated line to `.prettierignore`?

2024-12-19 13:05 UTC, christoph-jerolimov commented on workspaces/orchestrator/plugins/orchestrator-backend/static/generated/envelope/diagram/org.kie.workbench.common.stunner.sw.KogitoSWEditor/css/bootstrap-3.4.1.min.cache.css
It's you plugin but I would recommend to exclude this generated files. Wdyt?

2024-12-19 13:07 UTC, christoph-jerolimov commented on workspaces/repo-tools/packages/cli/src/lib/workspaces/templates/workspace/.gitignore.hbs
> +# macOS .DS_Store # Logs logs *.log npm-debug.log* yarn-debug.log*
This change (removing new lines) looks invalid to me.

2024-12-19 13:16 UTC, gciavarrini approved these changes
lgtm

2024-12-19 13:17 UTC, christoph-jerolimov commented on workspaces/orchestrator/plugins/orchestrator-backend/static/generated/envelope/combined.bundle.js
Based on the generated in .prettierignore I'm surprised to see this. I think you don't want format this.

2024-12-19 13:19 UTC, christoph-jerolimov commented on workspaces/repo-tools/packages/cli/src/lib/workspaces/templates/workspace/catalog-info.yaml.hbs
> +description: An example of a Backstage application. # Example for optional
That looks also broken to me.

Can you ignore *.hbs files?

2024-12-19 13:26 UTC, gciavarrini commented on workspaces/orchestrator/plugins/orchestrator-backend/static/generated/envelope/combined.bundle.js
Good catch! Also all the files in [orchestrator-common/src/generate](https://github.com/redhat-developer/rhdh-plugins/pull/212/files#diff-1ff6e60734aeec83e00940c38177b01c4d130f0443402955cfd7ae3960d42a76) should be ignored too.

2024-12-19 13:27 UTC, gciavarrini requested changes
ignore all the generated files and revert the changes

2024-12-19 13:35 UTC, mareklibra commented on workspaces/orchestrator/plugins/orchestrator-backend/static/generated/envelope/diagram/org.kie.workbench.common.stunner.sw.KogitoSWEditor/css/bootstrap-3.4.1.min.cache.css
If so then in a separate PR

2025-01-06 10:04 UTC, christoph-jerolimov commented on package.json
> +    "@backstage/catalog-model": "^1.7.2",
I think we should not add this kind of dependencies to the root package.json

2025-01-06 10:06 UTC, christoph-jerolimov requested changes
Hi @mareklibra, this looks much better now. But can you take a look into the root package.json and yarn.lock?

2025-01-06 10:06 UTC, christoph-jerolimov commented on package.json
> +    "@backstage/catalog-model": "^1.7.2",
I think we should not add this kind of dependencies to the root package.json

2025-01-06 10:06 UTC, christoph-jerolimov commented on package.json
> +    "cross-fetch": "^4.0.0",
Shouldn't be needed here.

2025-01-08 07:47 UTC, mareklibra commented
I don't see a commit adding those changes.
I will rebase due to merge conflicts, I guess those changes will disappear then.

2025-01-13 13:40 UTC, christoph-jerolimov approved these changes
Thanks for this PR and cleaning it up again and again :+1: 

Lgtm!

2025-01-13 14:20 UTC, merged