feat(bulk-import): update preview form to use separate formik context
redhat-developer/rhdh-plugins pull request #22
Opened 2024-11-05 16:17 UTC by debsmita1

## Hey, I just made a Pull Request!

**Resolves:**
https://issues.redhat.com/browse/RHIDP-3890

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [ ] Added or Updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

2024-11-06 23:55 UTC, christoph-jerolimov requested changes
This looks really clean and good to me.

You decided now to have one form per tab but save the errors in the page formik state?

When I click on preview, change the PR information, press save and reopen the drawer it shows always the default data. Maybe I'm testing it wrong. We can check that together maybe.

2024-11-06 23:55 UTC, christoph-jerolimov commented on workspaces/bulk-import/plugins/bulk-import/src/utils/repository-utils.tsx
> +        .map(([key, value]) => `${key?.trim()}: ${value?.trim()}`)
Should we filter keyValuePairs without key, or fall back to an empty string?

I'm worried that this will render undefined: undefined.

2024-11-06 23:55 UTC, christoph-jerolimov commented on workspaces/bulk-import/plugins/bulk-import/src/components/PreviewFile/PreviewPullRequestForm.test.tsx
> + */ import React from 'react';
```suggestion
 */
 import React from 'react';
```

2024-11-07 12:35 UTC, debsmita1 commented
> You decided now to have one form per tab but save the errors in the page formik state?
> 

Yes, in this way I can track all the field errors in single form/multiple sub forms

2024-11-07 19:52 UTC, christoph-jerolimov approved these changes
Lgtm!

2024-11-07 19:54 UTC, merged