docs(orchestrator): improve readme
redhat-developer/rhdh-plugins pull request #227
Opened 2024-12-29 10:43 UTC by batzionb

organized and updated the README
Link to branch to review properly: 
https://github.com/batzionb/rhdh-plugins/tree/improvereadme/workspaces/orchestrator#readme

2025-01-02 09:05 UTC, gciavarrini commented on workspaces/orchestrator/docs/Contributors.md
> +export AUTH_GITHUB_CLIENT_SECRET=...fill
link to explain how to get those secrets?

2025-01-02 09:05 UTC, gciavarrini commented on workspaces/orchestrator/plugins/orchestrator/docs/quickstart.md
you're removing this because it's a duplicate of https://www.rhdhorchestrator.io/main/docs/quickstart/
correct?

2025-01-02 09:05 UTC, gciavarrini commented on workspaces/orchestrator/README.md
> -## Context
why removing the `Context` section? I see that you're keeping some of the info here and there but I don't get why the removed info is unnecessary. Need clarifications here :)

2025-01-02 09:05 UTC, gciavarrini commented on workspaces/orchestrator/README.md
> +In addition to the main plugins, the architecture includes several isolated plugins that are imported by the above plugins:
is `above` correct?

2025-01-02 09:05 UTC, gciavarrini commented on workspaces/orchestrator/README.md
> +In addition to the main plugins, the architecture includes several isolated plugins that are imported by the above plugins:
doesn't apply anymore?

2025-01-02 09:07 UTC, batzionb commented on workspaces/orchestrator/README.md
> -## Context
I found it crowds the README and is related to Sonata itself and not to the plugin
But I can return it

2025-01-02 09:09 UTC, batzionb commented on workspaces/orchestrator/README.md
> +In addition to the main plugins, the architecture includes several isolated plugins that are imported by the above plugins:
It does, I thought better make it shorter

2025-01-02 09:11 UTC, batzionb commented on workspaces/orchestrator/plugins/orchestrator/docs/quickstart.md
yes, and also it has downstream screenshots

2025-01-02 12:08 UTC, batzionb commented on workspaces/orchestrator/README.md
> +In addition to the main plugins, the architecture includes several isolated plugins that are imported by the above plugins:
I meant that the following plugins are imported by backstage-plugin-orchestrator or backstage-plugin-orchestrator-backend

2025-01-02 15:46 UTC, batzionb commented on workspaces/orchestrator/docs/Contributors.md
> +export AUTH_GITHUB_CLIENT_SECRET=...fill
good point, I added instructions how to do this

2025-01-05 10:12 UTC, batzionb commented
@masayag 
can we get more another opinion on the README changes? especially making things shorter

2025-01-05 10:13 UTC, batzionb commented on workspaces/orchestrator/docs/Contributors.md
> +export AUTH_GITHUB_CLIENT_SECRET=...fill
does it look good now?

2025-01-05 10:50 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +## How to use the Git Hub identity provider
nit: s/Git Hub/GitHub

2025-01-05 10:50 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +### Create a Github OAuth App
s/Github/GitHub

2025-01-05 11:30 UTC, masayag requested changes

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +The orchestrator works harmoniously with other Backstage components such as the Software Catalog, permissions, and plugins as well as others. By leveraging its capabilities, organizations can orchest
What's the meaning of `working harmoniously with the Software Catalog` in this context? If the intention is to invoke software template as part of the workflow, or invoking other backend plugins - it should be stated clearly. This will highlight the fact that custom actions can be invoked by the orchestrator via a software template or as backend plugin if it has that API exposed.

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +   - Serves as a backend proxy between to SonataFlow.
should it be "between Backstand and SonataFlow" ?

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +The architecture adheres to standard Backstage plugin guidelines and requires the following plugins to be installed for proper functionality:
Would you like to add a link to https://www.rhdhorchestrator.io/main/docs/architecture/ ?

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +## Install as a static plugin
Why is this section needed?

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +- Docker up and running
Isn't podman supported as well? if not, should we provide here the command for running the container using podman from CLI instead of auto-start by the plugin?

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/README.md
> +For more information about audit logs in RHDH, please refer to [the official documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/getting_started_with_red_hat_develo
This can be updated to RHDH 1.4 doc:
https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html/audit_log/assembly-audit-log

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +Go to your Github account -> Setting -> Developer settings -> OAuth Apps -> New OAuth App.
s/Github/GitHub

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +Update [users.yaml](../users.yaml) to match you Github account. Put your github username in the metadata.name field, and you github email in spec.profile.email field.
s/Github/GitHub

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +Update [users.yaml](../users.yaml) to match you Github account. Put your github username in the metadata.name field, and you github email in spec.profile.email field.
Perhaps a snippet will be a simpler option of a User entity (just a thought)

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/docs/Contributors.md
> +## API Development instruction
Shouldn't this section go under orchestrator-common/README.md and be pointed from here or the other way around?

2025-01-05 11:30 UTC, masayag commented on workspaces/orchestrator/docs/extensibleForm.md
> +The [`orchestrator-form-react`](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator-form-react) plugin is designed to operate independently of the main orchestrator plugin.
https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator-form-react is depracated.

2025-01-05 11:57 UTC, batzionb commented on workspaces/orchestrator/README.md
> +## Install as a static plugin
this is for users installing on vanilla backstage

2025-01-05 11:58 UTC, batzionb commented on workspaces/orchestrator/README.md
> +- Docker up and running
the command is invoked in our code, currently it runs docker
we will need to change the code to support also podman

2025-01-05 11:58 UTC, batzionb commented on workspaces/orchestrator/docs/Contributors.md
> +Update [users.yaml](../users.yaml) to match you Github account. Put your github username in the metadata.name field, and you github email in spec.profile.email field.
you have it in ../users.yaml

2025-01-05 12:00 UTC, batzionb commented on workspaces/orchestrator/README.md
> +The orchestrator works harmoniously with other Backstage components such as the Software Catalog, permissions, and plugins as well as others. By leveraging its capabilities, organizations can orchest
you're right, this section isn't clear, and the integration with the software catalog isn't done
I can remove this

2025-01-05 12:00 UTC, batzionb commented on workspaces/orchestrator/README.md
> +## Install as a static plugin
all RHDH plugins include this in the docs

2025-01-05 12:02 UTC, batzionb commented on workspaces/orchestrator/README.md
> +- Docker up and running
I think better change the code to support both than to have the README explain what to do for podman, which is updating the autoStart to false and running the command

2025-01-08 12:02 UTC, mareklibra commented on workspaces/orchestrator/app-config.yaml
> -#     policies-csv-file: ../../plugins/orchestrator/docs/rbac-policy.csv
If relative link is used then it is from `rhdh-plugins/workspaces/orchestrator/packages/backend`

2025-01-08 12:04 UTC, mareklibra requested changes

2025-01-08 12:04 UTC, mareklibra commented on workspaces/orchestrator/app-config.yaml
> +#     policies-csv-file: ./docs/rbac-policy.csv
If a relative path is used then it is from the `rhdh-plugins/workspaces/orchestrator/packages/backend`.

I would keep the former value

2025-01-20 12:36 UTC, mareklibra commented on workspaces/orchestrator/README.md
> +The architecture adheres to standard Backstage plugin guidelines and requires the following plugins to be installed for proper functionality:
done

2025-01-20 12:36 UTC, mareklibra commented on workspaces/orchestrator/README.md
> +The orchestrator works harmoniously with other Backstage components such as the Software Catalog, permissions, and plugins as well as others. By leveraging its capabilities, organizations can orchest
done

2025-01-20 12:36 UTC, mareklibra commented on workspaces/orchestrator/README.md
> -## Context
partially reverted

2025-01-20 12:37 UTC, mareklibra commented on workspaces/orchestrator/README.md
> +   - Serves as a backend proxy between to SonataFlow.
yes

2025-01-20 12:38 UTC, mareklibra commented on workspaces/orchestrator/README.md
> +In addition to the main plugins, the architecture includes several isolated plugins that are imported by the above plugins:
rephrased

2025-01-20 12:40 UTC, mareklibra commented on workspaces/orchestrator/README.md
> +- Docker up and running
Right, so far docker is hard coded. It's for devmode only, let's improve for podman in a separate PR

2025-01-20 12:45 UTC, mareklibra commented on workspaces/orchestrator/docs/Contributors.md
> +Go to your Github account -> Setting -> Developer settings -> OAuth Apps -> New OAuth App.
done

2025-01-20 13:01 UTC, masayag commented
/lgtm

2025-01-20 14:05 UTC, masayag approved these changes

2025-01-20 14:16 UTC, gciavarrini approved these changes
/lgtm

2025-01-20 16:13 UTC, mareklibra approved these changes

2025-01-20 16:13 UTC, merged