chore: regenerate knip reports
redhat-developer/rhdh-plugins pull request #55
Opened 2024-11-19 17:14 UTC by 04kash

## Hey, I just made a Pull Request!

- Regenerate knip reports for all workspaces
- Make knip a devDependency instead of a dependency

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [ ] Added or Updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

2024-11-19 17:37 UTC, christoph-jerolimov requested changes
Hi, please remove at least the yarn blob (you can remove th dynamic-home-page workspace from your machine).

Also I see some false positives for "unused dependencies". I don't know how useful this is when the report is incorrect.

We can merge anyway but I think we should also check that we check that the file is accurate  (generate and ensure there is no diff)  on each PR.

2024-11-19 17:37 UTC, christoph-jerolimov commented on workspaces/dynamic-home-page/.yarn/install-state.gz
Can you remove this file  from your PR, its a left over after I renamed the `dynamic-home-page` workspace to `homepage`.

2024-11-19 17:37 UTC, christoph-jerolimov commented on workspaces/bulk-import/packages/app/knip-report.md
> +| @red-hat-developer-hub/backstage-plugin-bulk-import | package.json | error    |
Do you understand this false-positive?

The import is used in `workspaces/bulk-import/packages/app/src/App.tsx`

2024-11-19 17:37 UTC, christoph-jerolimov commented on workspaces/bulk-import/packages/backend/knip-report.md
> +| @red-hat-developer-hub/backstage-plugin-bulk-import-backend | package.json | error    |
Same here, it's used... Hmm :thinking:

2024-11-19 18:19 UTC, 04kash commented on workspaces/dynamic-home-page/.yarn/install-state.gz
Totally missed that, thanks @christoph-jerolimov !

2024-11-19 18:40 UTC, christoph-jerolimov approved these changes
Feel free to merge it when you're fine with it.

With two things we should follow-up:

1. Check/remove the false positives
2. Add this as a PR check (the idea is similar to the api-report.md, it makes changes like unused dependencies easier to notice)

2024-11-19 18:46 UTC, 04kash commented
> Add this as a PR check (the idea is similar to the api-report.md, it makes changes like unused dependencies easier to notice)
I was actually thinking of setting up a workflow to run this script as a cron job on a regular basis: https://github.com/redhat-developer/rhdh-plugins/blob/main/scripts/ci/generate-knip-report.js

But your suggestion to include it in the PR checks also sounds good

2024-11-20 17:31 UTC, 04kash commented
Merging this as is, will later open a follow-up PR to remove false positives.

2024-11-20 17:32 UTC, merged